@extends('layouts.remark')

@section('content')
    <h1>ProfitMiner.io Terms of Service / Acceptable Use Policy</h1>

    <p>By using any product or application of ProfitMiner.io, LLC (“ProfitMiner.io”, “us” or “we”; and such products
        and applications, as may be amended, augmented, enhanced or updated from time to time, collectively, the
        “Platform”), you are agreeing to be bound by the following terms and conditions (“Terms of Service”).</p>
    <p>ProfitMiner.io reserves the right to update and change the Terms of Service from time to time without notice.
        Any new features that amend, augment, enhance or update the current Platform, including the release of new
        tools and resources, shall be subject to the Terms of Service. Your continued use of the Platform after notice
        of any such changes has been provided on the ProfitMiner.io website (ProfitMiner.io) shall constitute your
        consent to such changes. You can review the most current version of the Terms of Service at any time at
        ProfitMiner.io/terms.</p>
    <p>By registering for a free trial of the ProftMiner.io Services, this agreement will also govern the free trial.</p>
    <p>By clicking the box, you agree to the terms of this agreement. If you are entering into this agreement on behalf
        of a company or other legal entity, you represent you have the authority to bind such entity and its affiliates
        to our terms and conditions.</p>
    <p>Violation of any of the terms below will result in the termination of your account with ProfitMiner.io and/or
        any obligation that ProfitMiner.io may have to you under these Terms of Service.</p>
    <p>You may not access the ProfitMiner.io Platform if You are Our direct competitor, except with Our prior written
        consent. In addition, you may not access the Platform for purposes of monitoring their availability,
        performance or functionality, or for any other benchmarking or competitive purposes.</p>


    <h3>Account Terms</h3>

    <ol>
        <li>You are responsible for maintaining the security of your account and password. ProfitMiner.io will not be
            liable for any loss or damage from your failure to comply with this security obligation.</li>
        <li>You are responsible for all data (including Data (as defined below)) of any sort uploaded to the Platform
            (“Content”) under your account and any activity that occurs under your account (even when Content is posted
            by others who have accounts under your account). You will not post any Content that is unlawful, offensive,
            threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s
            intellectual property.</li>
        <li>You may not use the Platform for any illegal, unethical or unauthorized purpose. You must not, in the use
            of the Platform, violate any laws in your jurisdiction (including but not limited to copyright laws).</li>
        <li>You shall have access to the ProfitMiner.io platform during the effective term and as more specifically set
            forth in the selected Service Level (the “Service”).</li>
        <li>All data or campaigns created in the platform during a Free Trial will be permanently lost unless you
            purchase a subscription to ProfitMiner.io’s platform before the end of the trial or you export and data
            from the platform prior to the end of the trial.</li>
    </ol>


    <h2>Software as a Service</h2>

    <ol>
        <li>You acknowledge and agree that you and any party authorized by to access your Content and Data from the Platform do so subject to the Limitation of Liability set forth below. As used herein, "Software" refers to any software, intellectual property, service and/or trademarks incorporated into or used by the Service. You shall not, and will not permit, assist, or allow others to, reverse engineer, decompile, decode, disassemble, re-engineer, or otherwise discover, recreate, or attempt to discover or recreate the Software or its source code. You shall not, either directly or indirectly, manipulate, modify and/or alter the Software. You shall not use the Software or the Service in any manner or for any purpose not otherwise expressly authorized by this Agreement.</li>
    </ol>

    <h2>Cancellation and Termination</h2>

    <ol>
        <li>All the identities and contact information that you provide for use by ProfitMiner.io in connection with the use of the Platform or Services (“Data”) will be deleted from the Platform within 90 days of end of a campaign or the termination of the agreement under which you use the Platform and/or the termination of your account. You understand that such Data cannot be recovered past the 90 days once such campaign ends, such agreement is terminated or your account is cancelled.</li>
        <li>You acknowledge and agree that your use of the Platform is subject to these Terms of Service, ProfitMiner.io’s Acceptable Use Policy and ProfitMiner.io’s Privacy Policy. ProfitMiner.io, in its sole discretion, has the right to suspend or terminate your account and refuse any and all current or future use of the Platform for any violation of these Terms of Service, ProfitMiner.io’s Acceptable Use Policy or ProfitMiner.io’s Privacy Policy.</li>
        <li>This Agreement commences on the date You accept it and continues until all User subscriptions granted in accordance with this Agreement have expired or been terminated. If you elect to the use Services for a free trial period and do not purchase a subscription before the end of that period, this Agreement will terminate at the end of the free trial period.</li>
        <li>If a customer is granted access to the ProfitMiner.io platform through the purchase of a third party reseller of the ProfitMiner.io platform, they will be granted temporary access to the ProfitMiner.io platform for the date of their promotion. To maintain ongoing access a subscription will be required by all customers.</li>
        <li>ProfitMiner.io may suspend, deny or terminate your access to all or part of our platform and/or services without prior notice if ProfitMiner.io believes, in its sole discretion that you violated any term of this agreement.</li>
    </ol>

    <h2>Payment</h2>

    <ol>
        <li>Full payment of fees payable to ProfitMiner.io is due before you may use the Platform or we perform any service for you, unless otherwise agreed, in writing, by you and ProfitMiner.io.</li>
        <li>You will provide us with updated and valid credit card information. You authorize Us to charge such credit card for all Services listed in the Order Form for any subscriptions, add on’s or products listed in your order Form. If the Order Form specifies that payment will be by a method other than credit card, an invoice will be sent to you in advance and must be paid in full for activation and access to services and that platform. Unless otherwise stated in the Order From, invoices charges are due net 30 days from the invoice date. You are responsible for providing complete and accurate billing and contact information to Us and notifying us of any changes to such information.</li>
        <li>All past due amounts will incur an interest charge of one and one-half percent (1/5%) per month (o the maximum rate permitted by Louisiana law) computed from the due date of each payment. You shall be liable for all arbitration, court, and/or related collection expenses.</li>
        <li>If your account is cancelled due to non payment a reactivation fee of $250 will be assessed to restore account access.</li>
    </ol>

    <h2>Modifications to the Platform and Prices</h2>

    <ol>
        <li>ProfitMiner.io reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Platform (or any part thereof) with or without notice.</li>
        <li>Unless otherwise agreed by you and ProfitMiner.io in writing, all pricing for use of the Platform is subject to change upon 30 days notice from us.</li>
        <li>ProfitMiner.io shall not be liable to you or to any third party for any modification, price change, suspension or discontinuance of the Platform.</li>
    </ol>

    <h2>Intellectual Property and Content Ownership</h2>

    <ol>
        <li>All content posted on the Platform must comply with U.S. copyright law.</li>
        <li>ProfitMiner.io does not pre-screen Content, but ProfitMiner.io and its designees have the right (but not the obligation) in their sole discretion to refuse or remove any Content that is made available through or in connection with the Platform.</li>
        <li>The look, feel, features and functionality of the Platform and Services are proprietary to ProfitMiner.io, LLC. You acknowledge and agree that the Platform and any Services, as well as software used in connection with the Platform and Services ("Software") contain proprietary and confidential information that is protected by applicable intellectual property and other laws, including pending patents. You further acknowledge and agree that Content contained in Web page copy or statistical, graphical, audio-visual or other information presented to you through the Platform and Services is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly permitted by applicable law or as expressly authorized by ProfitMiner.io or the applicable licensor (such as an advertiser), you agree not to modify, rent, lease, loan, sell, distribute, transmit, broadcast, publicly perform or create derivative works based on the Platform and Services, such Content or the Software, in whole or in part. ProfitMiner.io may monitor Your usage of the platform and use Your Data in an aggregate or anonymous manner, compile statistical and performance information related to the provision and operation of the Services and make such information publicly available, provided that such information does not incorporate You Data and/or identify Your Confidential Information. ProfitMiner.io retains all intellectual property rights in such information.</li>
        <li>ProfitMiner.io will exercise reasonable care to prevent any unauthorized person or entity from gaining access to data used by you to utilize the Service (“Your data”). ProfitMiner.io is not liable for any damage incurred by You or its authorized users using the platform including without limitation in connection with any unauthorized access to or disclosure of your Data, resulting from the actions of You, any third-party, or from the failure of electronic or other security measures.</li>
    </ol>

    <h2>Limitation of Liability</h2>

    <ol>
        <li>You acknowledge and agree that, to the fullest extent permitted by law, ProfitMiner.io shall not be liable for any direct, indirect, punitive, special, incidental, consequential, or exemplary damages (including, without limitation, loss of business, revenue, profits, goodwill, use, data, electronically transmitted orders, or other economic advantages) arising out of or in connection with your use of the platform or any services, even if ProfitMiner.io has previously been advised of, or reasonably could have foreseen, the possibility of such damages, however they arise, whether in breach of contract or in tort (including negligence), including without limitation damages due to: (a) the use of or the inability to use the Platform or any Services; (b) the cost of procurement of substitute services resulting from any defect in the Platform or Services; (c) statements or conduct of any third party on ProfitMiner.io’s website or the Platform, including without limitation unauthorized access to or alteration of transmissions or data, malicious or criminal behavior, or false or fraudulent transactions; or (d) content posted to the Platform by you or any third party.</li>
        <li>ProfitMiner.io shall not be liable for interruption of or delays in transmission or termination/cancellation of the Service caused by acts of God, fire, water, riots, acts of Governments, national emergency, acts or omissions of Internet backbone providers, or any other causes beyond ProfitMiner.io’s direct control.</li>
        <li>If you are dissatisfied with the Service or with any terms, conditions, rules, policies, guidelines, or practices of ProfitMiner.io your sole and exclusive remedy is to discontinue using the Service and request termination of the Agreement.</li>
        <li>The ProfitMiner.io Platform shall not be used as a data storage, archiving and/or back-up platform. Further, Client agrees to use the Platform only for the intended purpose of facilitating its media campaign(s).</li>
    </ol>

    <h2>General Conditions</h2>

    <ol>
        <li>Your use of the Platform and Services is solely at your risk.</li>
        <li>Technical support is provided on an account-by-account basis, funneled through ProfitMiner.io customer support representative.</li>
        <li>You understand and agree that ProfitMiner.io may use campaign results resulting from your use of the Platform and/or Services in use-case collateral and other marketing endeavors and can display your company name or entity as a customer on our customer list. You may request removal from the list by written request.</li>
        <li>You understand that ProfitMiner.io uses third-party vendors and hosting partners in connection with the Platform and, by your use of the Platform and/or Services, you agree to be bound by the terms of the service level agreements and terms of service of such partners.</li>
        <li>You must not modify, adapt or hack the Platform or modify another website so as to falsely imply that it is associated with Platform.</li>
        <li>You agree not to replicate, reproduce, duplicate, copy, sell, resell or exploit any portion of the Platform, use of the Platform or Services, or access to the Platform without the express written consent of ProfitMiner.io.</li>
        <li>ProfitMiner.io may, but have no obligation to, remove Content and terminate accounts containing Content that ProfitMiner.io determines in its sole discretion is unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party’s intellectual property or these Terms of Service.</li>
        <li>Verbal, physical, written or other abuse (including threats of abuse or retribution) of any ProfitMiner.io customer, employee, member, manager, officer or agent will result in the immediate termination of your account.</li>
        <li>You understand that the technical processing and transmission of the Platform, including your Content, may be transferred in unencrypted form and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</li>
        <li>No advice or information, whether oral or written, obtained through or from the service shall create any warranty not expressly stated in these Terms of Service.</li>
        <li>You must not upload, post, host, or transmit unsolicited email, SMSs, or “spam” messages to the Platform.</li>
        <li>You must not transmit any worms or viruses or any code of a destructive nature via the Platform.</li>
        <li>You expressly understand and agree that ProfitMiner.io shall not be liable for any direct, indirect, incidental, special, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses (even if ProfitMiner.io has been advised of the possibility of such damages), resulting from: (i) the use or the inability to use the Platform; (ii) the cost of procurement of substitute goods and platforms resulting from any goods, data, information or platforms purchased or obtained or messages received or transactions entered into through or from the Platform; (iii) unauthorized access to or alteration of your transmissions or data; (iv) statements or conduct of any third party on the Platform; (v) or any other matter relating to the Platform and your use of Services.</li>
        <li>The failure of ProfitMiner.io to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. Unless expressly agreed, in writing, between you and ProfitMiner.io, these Terms of Service constitute the entire agreement between you and ProfitMiner.io and govern your use of the Platform and any Services, and supersede any prior agreements between you and ProfitMiner.io (including, but not limited to, any prior versions of the Terms of Service).</li>
        <li>This Agreement and its performance shall be governed by the laws of the state of Louisiana, in the United States of America, without regard to its conflict of laws provisions. You consent and submit to the exclusive jurisdiction of the state and federal courts located in St. Tammany Parish, Louisiana, in the United States of America, in all questions and controversies arising out of your use of this website, the Services, and this Agreement. YOU AND ProfitMiner.IO HEREBY WAIVE TRIAL BY JURY IN ANY ACTION, PROCEEDING OR COUNTERCLAIM BROUGHT BY EITHER OF THE PARTIES HERETO AGAINST THE OTHER ON ANY MATTERS ARISING OUT OF OR IN ANY WAY CONNECTED WITH THIS AGREEMENT OR THE TRANSACTIONS CONTEMPLATED HEREUNDER, INCLUDING WITHOUT LIMITATION THE SERVICES.</li>
        <li>This Agreement constitutes the complete and exclusive understanding of the parties relating to the subject matter hereof and supersedes all prior or contemporaneous understandings, agreements and communications, whether written or oral, relating thereto. This Agreement may not be amended, altered, or changed except by a separate signature acknowledging those changes signed by the duly authorized representatives of both parties. In the event that any provision of this Agreement is held to be unenforceable, such provision will be construed as nearly as possible to reflect its original intent and the remainder of this Agreement will remain in full force and effect.</li>
    </ol>

    <h2>Acceptable Use Policy</h2>

    <ol>
        <li>ProfitMiner.IO strongly believes in people, commercial and social communication and freedom of expression as long as legal, ethical or generally accepted moral standards are not violated. In this Web site and as a company, ProfitMiner.IO is offering several services and software products that may expand your communication capabilities. ProfitMiner.IO trusts that these capabilities will be utilized to promote the flowing exchange of information and exercise your freedom of expression in accordance with this Acceptable Use Policy ("Policy"). Your violation of this Policy may result, among other things, in the suspension or cancellation of your access to the ProfitMiner.IO network, system, software, applications, services, products, various directories and listings, various message and news boards, tools, information and databases (together with the ProfitMiner.IO website, such resources will be referred to as the "ProfitMiner.IO Platform").</li>
        <li>ProfitMiner.IO does not actively monitor or exercise any editorial control over the content of any use or uses of the ProfitMiner.IO Platform or any messages or other material or information created, obtained or accessible through the ProfitMiner.IO Platform. However, ProfitMiner.IO reserves the right to remove, or discontinue the communication of, any material that it deems, in its sole discretion, to be actually or potentially illegal, of a nature that could subject ProfitMiner.IO to liability under any theory of law, in violation of this Policy or otherwise inappropriate.</li>
        <li>You agree not to post any message containing, or otherwise use, reference or communicate, any obscene or offensive images, symbols or language, or post, use, reference or communicate anywhere else on, through or in connection with the ProfitMiner.IO Platform any material that is defamatory, pornographic, racial, abusive or hateful, unauthorized, harassing, invading of anyone's privacy, encouraging of conduct that would constitute a criminal offense, giving rise to actual or potential civil liability, or otherwise violating any local, state, national or international law or regulation. You agree to use the ProfitMiner.IO Platform for professional use only and to refrain from any use for unlawful purposes.</li>
        <li>You further agree not to use the ProfitMiner.IO software nor any other software or application to attempt to override the ProfitMiner.IO privacy and security features or any other operational rule or process of the ProfitMiner.IO Platform including, without limitation, for spoofing, sniffing, eavesdropping, impostering or spamming other users, breaking passwords, harassment, fraud, forgery, electronic trespassing, tampering, hacking, nuking, and system contamination including, without limitation, introduction of viruses, worms and Trojan horses causing unauthorized damaging or harmful access and/or retrieval of information and data.</li>
        <li>You are solely responsible for ensuring that any material or information you submit, post or upload anywhere on, through or in connection with the ProfitMiner.IO Platform, including but not limited to text, video, audio and graphical images, does not violate the copyright, trademark, trade secret, or any other personal or proprietary rights of any third party or is posted with the permission of the owner(s) of such rights.</li>
        <li>Any electronic mail service and/or SMS text message service provided pursuant to this Agreement may only be used for lawful purposes and may not violate any local, state, federal or international laws that may apply to ProfitMiner.io, ProfitMiner.io’s third-party service providers, You or You’s end users. You and its end users are expected to be aware of and thereby comply with all applicable laws, rules and regulations concerning the use of electronically transmitted communications.</li>
        <li>You acknowledges that any electronic mail service and/or SMS text message service provided by ProfitMiner.io and/or its third-party agents are not considered a "secure communications medium" for any purpose whatsoever and that no expectation of privacy is afforded. Further, ProfitMiner.io and its third-party service providers are granted the right to access, copy and transmit copies of the content from electronic mail campaigns for the purpose of developing tools and systems to effectively monitor and control abuses.</li>
        <li>ProfitMiner.io may restrict, suspend or ban You from use of the shared IP pools or otherwise employ any mitigating remedy in the event that “spam” or any other complaints result from either You or its end users’ utilization of the Service. However, ProfitMiner.io, at its sole discretion, may offer You the opportunity to utilize and pay for a dedicated IP service in such instance.</li>
        <li>You shall undertake all reasonable measures to ensure the validity of those electronic mail addresses and telephone numbers for SMS text messaging to which any data or information is transmitted through the Service</li>
        <li>ProfitMiner.io, at its sole discretion, may unsubscribe any electronic mail address from where a spam complaint has initiated. However, You may, within thirty (30) days following such action, direct a written request to ProfitMiner.io, requesting reinstatement of that specific electronic mail address by providing justification for such reinstatement.</li>
        <li>All recipients of electronic mail and/or SMS messages must have opted to receive them, and, on the initial message be prompted to accept ongoing communications. All messages must contain a mechanism for subscribers to opt out from further messages by the use of industry-standard keywords such as “STOP”. Further, opting in to a specific mobile marketing program does not give permission to be sent messages from any other campaign not specifically related to that program.</li>
        <li>ANY DIRECT, INDIRECT OR ATTEMPTED VIOLATIONS OF THE AUP SHALL BE CONSIDERED A MATERIAL BREACH OF THE POLICY AND THE SERVICES MAY, AT ProfitMiner.IO’S SOLE DISCRETION AND ABSENT PRIOR NOTICE, BE IMMEDIATELY TERMINATED, SUSPENDED, RESTRICTED OR MODIFIED</li>
        <li>You agree that by posting any material or information anywhere within or connected to the ProfitMiner.IO Platform you are allowing ProfitMiner.IO the use of your copyright and any other proprietary right in the posted material or information.</li>
        <li>IT IS SOLELY YOUR RESPONSIBILITY TO EVALUATE THE QUALITY, ADEQUACY, ACCURACY, COMPLETENESS, CURRENTNESS, VALIDITY AND USEFULNESS OF ALL OPINIONS, ADVICE, SERVICES, AND OTHER INFORMATION OBTAINED OR ACCESSIBLE THROUGH OR IN CONNECTION WITH THE ProfitMiner.IO PLATFORM.</li>
        <li>You agree to indemnify ProfitMiner.IO, its employees, agents, and representatives, and to hold them harmless, from any and all losses, claims and liabilities (including attorneys fees) which may arise from your submissions, campaigns, communications, posting of information or deletion thereof, from your use of any of the ProfitMiner.IO Platform or any other service and/or material obtained from or accessible through any services provided on the ProfitMiner.IO website, or from your breach of these rules or any other agreement between you and ProfitMiner.IO. You further agree that ProfitMiner.IO is not responsible, and shall have no liability to you or anyone else, for any material posted by others, including defamatory, offensive, or illicit material, and that the risk of damage from such material rests entirely with you.</li>
        <li>You agree not to disrupt or interfere with the ProfitMiner.IO Platform or any other services provided on this website, nor to alter or tamper with any information or materials on or associated thereto. You agree not to attempt to penetrate security measures of ProfitMiner.IO Platform, whether or not the intrusion results in corruption or loss of data.</li>
        <li>The access to ProfitMiner.IO's various directories, databases and listings is provided by ProfitMiner.IO as a convenience. ProfitMiner.IO users and those wishing to contact ProfitMiner.IO users are granted limited access to ProfitMiner.IO's various directories, databases and listings solely for the purpose of allowing more convenient personal communications over the ProfitMiner.IO Platform. Any other use or attempt to use ProfitMiner.IO's various directories, databases and listings [for commercial] [?], or other purposes or for systematic retrieval of data and information stored in ProfitMiner.IO's various directories, databases and listings and any kind of copying or reproduction of the data, or any part thereof, stored in ProfitMiner.IO's various directories, databases and listings to any other location or server for further reproduction or distribution is unauthorized and strongly prohibited.</li>
        <li>You acknowledge that you are expressly prohibited from utilizing the ProfitMiner.IO Message Boards, ProfitMiner.IO servers, ProfitMiner.IO End-User software nor any of the ProfitMiner.IO Platform in connection with data mining of any kind, the sending of unsolicited electronic mail or other forms of messages, whether commercial or not, to a large number of recipients.</li>
        <li>You agree to refrain from revealing your password to others or allowing others to use your ProfitMiner.IO account.</li>
        <li>You agree to refrain from forging any message header, in part or whole, of any electronic transmission, originating or passing through the ProfitMiner.IO Platform, distributing viruses to, from or through the ProfitMiner.IO Platform and allowing access to the ProfitMiner.IO servers through your ProfitMiner.IO account for the purpose of operating a server of any type or for any other purpose which is not common personal use.</li>
        <li>ProfitMiner.IO has no practical ability to restrict all conduct, communications or content which might violate this Policy prior to its transmission on or through the ProfitMiner.IO Platform, nor can ProfitMiner.IO ensure prompt removal of any such communications or content after transmission or posting. Accordingly, ProfitMiner.IO does not assume liability to users or others for any failure to enforce the terms of this Policy.</li>
        <li>If any part of this Policy is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.</li>
        <li>Any reference made in this Policy to ProfitMiner.IO shall be deemed to have been made to ProfitMiner.IO, its subsidiaries, successors, assignees, affiliates as well as any company that controls ProfitMiner.IO, directly or indirectly, and any other subsidiary of that controlling company.</li>
        <li>ProfitMiner.IO may change from time to time the ProfitMiner.IO Terms of Service including this Policy, the ProfitMiner.IO Privacy Policy and any other document available on or through http://ProfitMiner.IO/terms (collectively and separately referred to as the "ProfitMiner.IO Terms of Service"). You agree that your continued use of the ProfitMiner.IO Platform, beyond a period of 30 days after a notice of such change has been provided on the ProfitMiner.IO network or Web site for the first time, shall constitute your consent to the new or revised ProfitMiner.IO Terms of Service, including this Policy.</li>
        <li>In case of contradiction between any provision of this Policy and any provision of the ProfitMiner.IO Help File, the provision of this Policy shall prevail, unless the provision of the ProfitMiner.IO Help File reflects a narrower responsibility on behalf of ProfitMiner.IO than the relevant provision of this Policy.</li>
    </ol>
@endsection